name: your-workflow-name
on: [push]
jobs:
  run:
    runs-on: [self-hosted]
    # optionally use a convenient Ubuntu LTS + DVC + CML image
     #container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token : ${{ secrets.GPU_TOKEN }}
        run: |
          # Your ML workflow goes here
          CODEBLOCK="\`\`\`"
          echo $CODEBLOCK > report.md
          nvidia-smi >> readme.md
          echo $CODEBLOCK >> report.md
          
          cml-send-comment report.md
